import { rgb } from 'pdf-lib'
import {
    randomNumber,
    dateFormat,
    dayCount,
    standartDate,
    monthNameDate,
    today,
    monthNameDateOnly,
} from '../formats.js'

import { centeredText } from '../functions.js'


export const can = [
    {
        width: 70,
        height: 12,
        x: 471,
        y: 796,
        bgColor: rgb(1, 1, 1),
        textX: 472.5, 
        textY: 798.5,
        size: 9.5,
        textColor: rgb(0, 0.61, 1),
        description: 'Код подтверждения',
        font: 'robotoBold',
        content: () => randomNumber("0000") + "." + randomNumber("000") + "." + randomNumber("000")
    },
    {
        width: 60,
        height: 12,
        x: 417,
        y: 784,
        bgColor: rgb(1, 1, 1),
        textX: 418, 
        textY: 786.5,
        size: 9.5,
        textColor: rgb(0, 0.61, 1),
        description: 'ПИН-код',
        font: 'robotoBold',
        content: () => randomNumber("0000")
    },
    {
        width: 35,
        height: 20,
        x: 343,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(dateFormat(ctx.dateFrom.value).day, 359, ctx.font['robotoBold'], 18.5),
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - день',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateFrom.value).day
    },
    {
        width: 60,
        height: 9,
        x: 330,
        y: 733,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(dateFormat(ctx.dateFrom.value).monthName.ruCaps, 359, ctx.font['robotoBold'], 8),
        textY: 734,
        size: 8,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - месяц',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateFrom.value).monthName.ruCaps
    },
    {
        width: 45,
        height: 8,
        x: 333,
        y: 721.5,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(ctx.text, 358, ctx.font['Brygada1918'], 7),
        textY: 723.5,
        size: 7,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - день недели',
        font: 'Brygada1918',
        content: (ctx) => dateFormat(ctx.dateFrom.value).weekday.ru
    },
    {
        width: 35,
        height: 20,
        x: 425,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(dateFormat(ctx.dateTo.value).day, 440, ctx.font['robotoBold'], 18.5),
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - день',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateTo.value).day
    },
    {
        width: 60,
        height: 9,
        x: 410,
        y: 733,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 434.5, 
        textX: (ctx) => centeredText(dateFormat(ctx.dateTo.value).monthName.ruCaps, 440, ctx.font['robotoBold'], 8),
        textY: 734,
        size: 8,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - месяц',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateTo.value).monthName.ruCaps
    },
    {
        width: 45,
        height: 8,
        x: 414,
        y: 721.5,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(ctx.text, 442, ctx.font['Brygada1918'], 7), 
        textY: 723.5,
        size: 7,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - день недели',
        font: 'Brygada1918',
        content: (ctx) => dateFormat(ctx.dateTo.value).weekday.ru
    },
    {
        width: 15,
        height: 20,
        x: 500,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 499, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Комнат',
        font: 'robotoBold',
        content: () => '1'
    },
    {
        width: 30,
        height: 20,
        x: 529,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 530, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Кол-во ночей',
        font: 'robotoBold',
        content: (ctx) => dayCount(ctx.dateFrom.value, ctx.dateTo.value)
    },
    {
        width: 150,
        height: 35,
        x: 405,
        y: 338,
        bgColor: rgb(1, 1, 1),
        description: 'Стоимость отмены'
    },
    {
        width: 298,
        height: 10,
        x: 85,
        y: 393,
        bgColor: rgb(1, 1, 1),
        textX: 86, 
        textY: 395.3,
        size: 7.5,
        textColor: rgb(0, 0, 0),
        description: 'Гости',
        font: 'robotoRegular',
        content: (ctx) => ctx.tourist.length == 2 ? ctx.tourist[0].name + ', ' + ctx.tourist[1].name : ctx.tourist[0].name
    },
]