import { rgb } from 'pdf-lib'
import {
    randomNumber,
    dateFormat,
    dayCount,
} from '../formats.js'

import { centeredText } from '../functions.js'


export const pek = [
    {
        width: 70,
        height: 12,
        x: 497,
        y: 796,
        bgColor: rgb(1, 1, 1),
        textX: 497, 
        textY: 799,
        size: 9,
        textColor: rgb(0, 0.61, 1),
        description: 'Код подтверждения',
        font: 'robotoBold',
        content: () => randomNumber("0000") + "." + randomNumber("000") + "." + randomNumber("000")
    },
    {
        width: 60,
        height: 12,
        x: 449,
        y: 784,
        bgColor: rgb(1, 1, 1),
        textX: 450, 
        textY: 786.5,
        size: 9,
        textColor: rgb(0, 0.61, 1),
        description: 'ПИН-код',
        font: 'robotoBold',
        content: () => randomNumber("0000")
    },
    {
        width: 35,
        height: 20,
        x: 343,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 348, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - день',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateFrom.value).day
    },
    {
        width: 35,
        height: 9,
        x: 349,
        y: 733,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 350, 
        textY: 734,
        size: 8,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - месяц',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateFrom.value).monthName.enCaps
    },
    {
        width: 35,
        height: 8,
        x: 344,
        y: 721.5,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(ctx.text, 357, ctx.font['Brygada1918'], 7),
        textY: 723.5,
        size: 7,
        textColor: rgb(0, 0, 0),
        description: 'Заезд - день недели',
        font: 'Brygada1918',
        content: (ctx) => dateFormat(ctx.dateFrom.value).weekday.en
    },
    {
        width: 35,
        height: 20,
        x: 425,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 431, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - день',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateTo.value).day
    },
    {
        width: 35,
        height: 9,
        x: 430,
        y: 733,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 434.5, 
        textY: 734,
        size: 8,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - месяц',
        font: 'robotoBold',
        content: (ctx) => dateFormat(ctx.dateTo.value).monthName.enCaps
    },
    {
        width: 35,
        height: 8,
        x: 425,
        y: 721.5,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: (ctx) => centeredText(ctx.text, 442, ctx.font['Brygada1918'], 7),
        textY: 723.5,
        size: 7,
        textColor: rgb(0, 0, 0),
        description: 'Выезд - день недели',
        font: 'Brygada1918',
        content: (ctx) => dateFormat(ctx.dateTo.value).weekday.en
    },
    {
        width: 15,
        height: 20,
        x: 500,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 499, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Комнат',
        font: 'robotoBold',
        content: () => '1'
    },
    {
        width: 30,
        height: 20,
        x: 529,
        y: 744,
        bgColor: rgb(0.949, 0.957, 0.965),
        textX: 530, 
        textY: 746,
        size: 18.5,
        textColor: rgb(0, 0, 0),
        description: 'Кол-во ночей',
        font: 'robotoBold',
        content: (ctx) => dayCount(ctx.dateFrom.value, ctx.dateTo.value)
    },
    {
        width: 160,
        height: 40,
        x: 390,
        y: 327,
        bgColor: rgb(1, 1, 1),
        description: 'Стоимость отмены'
    },
    {
        width: 290,
        height: 10,
        x: 90,
        y: 388,
        bgColor: rgb(1, 1, 1),
        textX: 91, 
        textY: 390.8,
        size: 7.5,
        textColor: rgb(0, 0, 0),
        description: 'Гости',
        font: 'robotoRegular',
        content: (ctx) => ctx.tourist.length == 2 ? ctx.tourist[0].name + ', ' + ctx.tourist[1].name : ctx.tourist[0].name
    },
]