import { rgb } from 'pdf-lib'
import {
    randomNumber,
    dateFormat,
    dayCount,
    standartDate,
    monthNameDate,
    today,
    monthNameDateOnly
} from '../formats.js'


export const vvopek = [
    {
        width: 130,
        height: 25,
        x: 34,
        y: 770,
        bgColor: rgb(1, 1, 1),
        textX: 36, 
        textY: 780,
        size: 14,
        textColor: rgb(0, 0, 0),
        description: 'Номер заказа',
        font: 'golosText',
        content: () => "№ " + randomNumber("0000000000")
    },
    {
        width: 290,
        height: 17,
        x: 36,
        y: 705,
        bgColor: rgb(1, 1, 1),
        textX: 37, 
        textY: 709,
        size: 10,
        textColor: rgb(0, 0, 0),
        description: 'Имя туриста',
        font: 'golosText',
        content: (ctx) => ctx.tourist.name
    },
    {
        width: 100,
        height: 17,
        x: 349,
        y: 705,
        bgColor: rgb(1, 1, 1),
        textX: 349, 
        textY: 709,
        size: 10,
        textColor: rgb(0, 0, 0),
        description: 'Дата рождения',
        font: 'golosText',
        content: (ctx) => monthNameDate(ctx.tourist.date, "ru")
    },
    {
        width: 100,
        height: 17,
        x: 453,
        y: 705,
        bgColor: rgb(1, 1, 1),
        textX: 453, 
        textY: 709,
        size: 10,
        textColor: rgb(0, 0, 0),
        description: 'Паспорт',
        font: 'golosText',
        content: (ctx) => ctx.tourist.passport
    },
    {
        width: 60,
        height: 17,
        x: 140.5,
        y: 545,
        bgColor: rgb(1, 1, 1),
        textX: 140.5, 
        textY: 548,
        size: 10,
        textColor: rgb(0, 0, 0),
        description: 'Номер брони 1',
        font: 'golosText',
        content: () => randomNumber("AA0A0A")
    },
    {
        width: 60,
        height: 10,
        x: 244,
        y: 528.5,
        bgColor: rgb(1, 1, 1),
        textX: 244.5, 
        textY: 530.5,
        size: 7.3,
        textColor: rgb(0, 0, 0),
        description: 'Дата вылета',
        font: 'golosText',
        content: (ctx) => monthNameDate(ctx.dateFrom.value, "ru")
    },
    {
        width: 60,
        height: 10,
        x: 426,
        y: 528.5,
        bgColor: rgb(1, 1, 1),
        textX: 427.5, 
        textY: 530.5,
        size: 7.3,
        textColor: rgb(0, 0, 0),
        description: 'Дата посадки',
        font: 'golosText',
        content: (ctx) => monthNameDate(ctx.dateFrom.value, "ru")
    },
    {
        width: 60,
        height: 17,
        x: 140.5,
        y: 375,
        bgColor: rgb(1, 1, 1),
        textX: 140.5, 
        textY: 378,
        size: 10,
        textColor: rgb(0, 0, 0),
        description: 'Номер брони 2',
        font: 'golosText',
        content: () => randomNumber("AA0A0A")
    },
    {
        width: 60,
        height: 10,
        x: 244,
        y: 359,
        bgColor: rgb(1, 1, 1),
        textX: 244.5, 
        textY: 361,
        size: 7.3,
        textColor: rgb(0, 0, 0),
        description: 'Дата вылета',
        font: 'golosText',
        content: (ctx) => monthNameDate(ctx.dateTo.value, "ru")
    },
    {
        width: 60,
        height: 10,
        x: 426,
        y: 359,
        bgColor: rgb(1, 1, 1),
        textX: 427.5, 
        textY: 361,
        size: 7.3,
        textColor: rgb(0, 0, 0),
        description: 'Дата посадки',
        font: 'golosText',
        content: (ctx) => monthNameDate(ctx.dateTo.value, "ru")
    },
    {
        width: 60,
        height: 10,
        x: 31,
        y: 225,
        bgColor: rgb(1, 1, 1),
        textX: 32, 
        textY: 227.5,
        size: 7.5,
        textColor: rgb(0, 0, 0),
        description: 'Дата покупки',
        font: 'golosText',
        content: () => monthNameDate(today(), "ru")
    },
    {
        width: 30,
        height: 10,
        x: 200,
        y: 225,
        bgColor: rgb(1, 1, 1),
        textX: 200, 
        textY: 227.5,
        size: 7.5,
        textColor: rgb(0.2, 0.2, 0.2),
        description: 'Карта',
        font: 'golosTextMedium',
        content: () => "*" + randomNumber("0000")
    },
]